services:
  - type: web
    name: sustainability-chatbot-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    repo: https://github.com/yourusername/your-repo-name
    branch: main
    rootDir: backend
